### ISSUE TITLE
The scripts run but no plots are produced.

### ISSUE THREAD

**Issue by kdbchau** [BPerezLamarque/ABDOMEN#1]
Not sure where the issue is but I tried the ABDOMEN.R script with my own data, everything ran fine. However following the README to produce plots, I only get my Pagel's lambda values and no plots are produced.

Are the plots shown in the readme produced separately or should be generated automatically after running ABDOMEN_extract_lambda? If those are produced separately, code to generate those plots should be included in the tutorial to see if we can reproduce the same figures.

**Comment by BPerezLamarque** [comment]
Dear Katherine, 

Yes all the plots are generated as PDF files and should be stored in the folder "plot_ABDOMEN/", which should be created in your working directory (specified by default in the variable "code_path"). I will clarify this in the tutorial. Let me know if that worked correctly. 

Don't hesitate if you have any other questions running ABDOMEN!

All best, 
Benoît

**Comment by kdbchau** [comment]
Oh! Yes there is a folder there - wow how did I miss that. 
Thanks so much for clearing that up!

**Comment by kdbchau** [comment]
For the tree figure with the pie charts, the second figure with the tip labels mine is all cut off. I've been trying to adjust the settings but I am getting the same output where my figure is just cut off at the end so I cannot fully see my species labels. Do you have a suggestion on how I can view these figures within RStudio without automatically saving it (so I can try adjusting the margins better?)

**Comment by BPerezLamarque** [comment]
It seems that the plotting issue of the species names comes from the package ggtree. I recommend you copy paste the content of the function ABDOMEN_process_output and customise its content (e.g. you can simply remove the pdf() function to directly see the plots in RStudio). And about ggtree, you can try reducing the size of the labels (e.g. replacing geom_tiplab(size=2) by geom_tiplab(size=0.5) ) and/or adjusting the margins of the plot (e.g. with the xlim() function of ggtree).
